### PR TITLE
Don't ignore if `submoduleName` has an extension

### LINKED ISSUE #2: Not working accessing files in scoped packages
When accessing to a file in a package without `exports` field (using `main` instead), it can't find them. Something like `@mafalda/fsset/waiting.js` resolves to `null` instead of the path of the `waiting.js` inside the `@mafalda/fsset` package.

### PR DESCRIPTION
**Pull request by piranna**
Fix #2

### CODE REVIEW

**Comment by k-g-a** [comment]
I'm sorry for being late, will merge & publish by tomorrow. Thanks!

**Comment by piranna** [comment]
welcome :-)

**Comment by piranna** [comment]
Thank you :-) When will this be published?

**Comment by piranna** [comment]
Oh, I've seen it's published as `1.0.5`, thanks :-)

**Pull request merged**
